export default {
  PASSWORD_IS: 'Вы уже получали пароль!',
  NOT_EMAIL: 'Необходимо ввести Email!',
  WRONG_LOGIN: 'Неверный email или пароль!',
  DEACTIVE: 'Ваш аккаунт деактивирован, обратитесь к администрации!',
  PASSWORD_NULL: 'Вы еще не получили пароль!',
  PASSWORD_CONFLICT: 'Пароли не совпадают!',
  PASSWORD_EDITED: 'Ваш пароль изменен!',
  ERR_INPUT_EMAIL: 'Необходимо ввести почту!',
  NOT_EXIST_USER: 'Пользователь с такой почтой не существует в системе!',
  SENDED_EMAIL_REGISTER: 'На Вашу почту отправлено письмо с дальнейшей инструкцией! Если письмо не приходит, проверьте папку "Спам"!',
  SENDED_EMAIL_RESET: 'Письмо для восстановления пароля отправлено на почту!',
  NOT_FOUND: 'Пользователь не найден!',
  TITLE_LOGIN_PASSWORD: 'Получение пароля!',
  TITLE_RESET: 'Восстановление пароля',
  SRC_RESET: __dirname + '/templates/reset.html',
  SRC_LOGIN_PASSWORD: __dirname + '/templates/new.html',
}